spring:
  application:
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/pos_management_db?createDatabaseIfNotExist=false
    username: root
    password: test$123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
        testOnBorrow: true
        maxActive: 10
        minIdle: 5
        maxWait: 30000
        validationQuery: SELECT 1
        removeAbandoned: true
        removeAbandonedTimeout: 60
        testWhileIdle: true
        logAbandoned: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl